#!/usr/bin/env python3
"""Encrypt strings for C++ obfuscation using AES-128-ECB.

Outputs C++ byte arrays that can be pasted into obfuscation.h.
Requires: pip install pycryptodome
"""
from Crypto.Cipher import AES
import sys

# Same key as HARDCODED_AES_KEY in crypto.cpp: "OplayDrmPackerKy"
KEY = bytes([0x4F, 0x70, 0x6C, 0x61, 0x79, 0x44, 0x72, 0x6D,
             0x50, 0x61, 0x63, 0x6B, 0x65, 0x72, 0x4B, 0x79])


def pad_pkcs7(data: bytes) -> bytes:
    pad_len = 16 - (len(data) % 16)
    return data + bytes([pad_len] * pad_len)


def encrypt(plaintext: str) -> bytes:
    cipher = AES.new(KEY, AES.MODE_ECB)
    return cipher.encrypt(pad_pkcs7(plaintext.encode("utf-8")))


# Strings that need to be obfuscated in the native binary.
# These are Android class/method names used via JNI reflection.
STRINGS = {
    "MEDIADRM_CLASS": "android/media/MediaDrm",
    "GET_KEY_REQUEST": "getKeyRequest",
    "GET_KEY_REQUEST_SIG": "([B[BLjava/lang/String;ILjava/util/HashMap;)Landroid/media/MediaDrm$KeyRequest;",
    "PROVIDE_KEY_RESPONSE": "provideKeyResponse",
    "PROVIDE_KEY_RESPONSE_SIG": "([B[B)[B",
    "ACTIVITY_THREAD_CLASS": "android/app/ActivityThread",
    "CURRENT_ACTIVITY_THREAD": "currentActivityThread",
    "CURRENT_ACTIVITY_THREAD_SIG": "()Landroid/app/ActivityThread;",
    "GET_APPLICATION": "getApplication",
    "GET_APPLICATION_SIG": "()Landroid/app/Application;",
    "BUILD_CLASS": "android/os/Build",
    "BUILD_VERSION_CLASS": "android/os/Build$VERSION",
    "CONTENT_RESOLVER_CLASS": "android/content/ContentResolver",
    "SETTINGS_SECURE_CLASS": "android/provider/Settings$Secure",
    "GET_CONTENT_RESOLVER": "getContentResolver",
    "GET_CONTENT_RESOLVER_SIG": "()Landroid/content/ContentResolver;",
    "GET_STRING": "getString",
    "GET_STRING_SIG": "(Landroid/content/ContentResolver;Ljava/lang/String;)Ljava/lang/String;",
    "ANDROID_ID": "android_id",
    "PACKAGE_MANAGER_CLASS": "android/content/pm/PackageManager",
    "PACKAGE_INFO_CLASS": "android/content/pm/PackageInfo",
    "GET_PACKAGE_MANAGER": "getPackageManager",
    "GET_PACKAGE_MANAGER_SIG": "()Landroid/content/pm/PackageManager;",
    "GET_PACKAGE_NAME": "getPackageName",
    "GET_PACKAGE_NAME_SIG": "()Ljava/lang/String;",
    "GET_PACKAGE_INFO": "getPackageInfo",
    "GET_PACKAGE_INFO_SIG": "(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;",
}

if __name__ == "__main__":
    print("// Generated by tools/encrypt_strings.py — DO NOT edit manually")
    print("// Regenerate with: python3 tools/encrypt_strings.py")
    print()
    for name, value in STRINGS.items():
        enc = encrypt(value)
        hex_arr = ", ".join(f"0x{b:02x}" for b in enc)
        print(f"static const uint8_t OBF_{name}[] = {{{hex_arr}}};")
        print(f"static const size_t OBF_{name}_LEN = {len(enc)};")
        print()
